#!/usr/bin/env bash

set -euo pipefail

log_error() {
  echo "ERROR: $1" >&2
}

if [[ -z "$CREDENTIALS_DIRECTORY" ]]; then
  log_error "CREDENTIALS_DIRECTORY not found. Run this via systemd."
  exit 1
fi

CF_ZONE_ID=$(cat "$CREDENTIALS_DIRECTORY/CF_ZONE_ID")
CF_RECORD_ID_4=$(cat "$CREDENTIALS_DIRECTORY/CF_RECORD_ID_4")
CF_RECORD_ID_6=$(cat "$CREDENTIALS_DIRECTORY/CF_RECORD_ID_6")
CF_API_TOKEN=$(cat "$CREDENTIALS_DIRECTORY/CF_API_TOKEN")
IPINFO_API_TOKEN=$(cat "$CREDENTIALS_DIRECTORY/IPINFO_API_TOKEN")

update_dns_record() {
  local type=$1 # 'v4' | 'v6'
  local record_id=$2
  local current_ip

  # NOTE: `xh` uses the `--check-status` option by default, meaning it will exit with an error
  #       status code on non-200 responses

  current_ip=$(xh -b --timeout 10 https://"$type".api.ipinfo.io/lite/me \
    -A bearer --auth "$IPINFO_API_TOKEN" | jq -r .ip) || {
    log_error "Could not fetch current WAN IP$type"
    return 1
  }

  local get_resp
  get_resp=$(xh -b --timeout 10 GET "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records/$record_id" \
    -A bearer --auth "$CF_API_TOKEN") || {

    if [ "$(jq -r .success <<<"$get_resp")" != 'true' ]; then
      log_error "Falied to check IP$type DNS record: $(jq -c .errors <<<"$get_resp")"
      return 1
    fi
  }

  local registered_ip
  registered_ip=$(jq -r .result.content <<<"$get_resp")

  if [ "$registered_ip" == "$current_ip" ]; then
    echo "IP$type ($current_ip) is unchanged. No update needed."
    return 0
  fi

  local patch_resp
  patch_resp=$(xh -b --timeout 10 PATCH "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records/$record_id" \
    -A bearer --auth "$CF_API_TOKEN" \
    content="$current_ip") || {

    if [ "$(jq -r .success <<<"$patch_resp")" != 'true' ]; then
      log_error "Cloudflare failed to update IP$type DNS record: $(jq -c .errors <<<"$patch_resp")"
      return 1
    fi
  }

  echo "IP$type ($current_ip) has changed. Record updated successfully."
}

update_dns_record 'v4' "$CF_RECORD_ID_4" || exit 1
update_dns_record 'v6' "$CF_RECORD_ID_6" || exit 1
